---
controller_hosts:
 - name: lab_host1
   inventory: Lab Inventory
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: alab_host2
   inventory: Lab Inventory
...
