---
controller_hosts:
 - name: endurance
   inventory: Home Lab Inventory
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: akira
   inventory: Home Lab Inventory
...
